-- Dados fictícios para exemplo
INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES (1, 'Austin', 'TX', 30, -97);
INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES (2, 'El Paso', 'TX', 31, -106);
INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES (3, 'Orlando', 'FL', 28, -81);
INSERT INTO STATION (ID, CITY, STATE, LAT_N, LONG_W) VALUES (4, 'LA', 'CA', 34, -118);